"""add_responsibility_assignment_table_and_extend_user_roles

Revision ID: 14985a79356b
Revises: 7075106367ed
Create Date: 2026-01-23 13:16:47.767600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14985a79356b'
down_revision: Union[str, Sequence[str], None] = '7075106367ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new values to UserRole enum
    # PostgreSQL doesn't allow adding enum values in a transaction, so we do it carefully
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'super_admin'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'staff'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'pi'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'researcher'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'student'")

    op.create_table('responsibility_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('SCIENTIFIC_PROJECT', 'PROJECT_ACTIVITY', 'PUBLICATION', 'WORK_PACKAGE', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('raci_role', sa.Enum('R', 'A', 'C', 'I', name='racirole'), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['academic_members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_member_lookup', 'responsibility_assignments', ['member_id'], unique=False)
    op.create_index('idx_resource_lookup', 'responsibility_assignments', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_user_lookup', 'responsibility_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_responsibility_assignments_id'), 'responsibility_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_responsibility_assignments_member_id'), 'responsibility_assignments', ['member_id'], unique=False)
    op.create_index(op.f('ix_responsibility_assignments_raci_role'), 'responsibility_assignments', ['raci_role'], unique=False)
    op.create_index(op.f('ix_responsibility_assignments_resource_id'), 'responsibility_assignments', ['resource_id'], unique=False)
    op.create_index(op.f('ix_responsibility_assignments_resource_type'), 'responsibility_assignments', ['resource_type'], unique=False)
    op.create_index(op.f('ix_responsibility_assignments_user_id'), 'responsibility_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Note: Removed auto-generated unrelated schema changes to avoid migration conflicts
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responsibility_assignments_user_id'), table_name='responsibility_assignments')
    op.drop_index(op.f('ix_responsibility_assignments_resource_type'), table_name='responsibility_assignments')
    op.drop_index(op.f('ix_responsibility_assignments_resource_id'), table_name='responsibility_assignments')
    op.drop_index(op.f('ix_responsibility_assignments_raci_role'), table_name='responsibility_assignments')
    op.drop_index(op.f('ix_responsibility_assignments_member_id'), table_name='responsibility_assignments')
    op.drop_index(op.f('ix_responsibility_assignments_id'), table_name='responsibility_assignments')
    op.drop_index('idx_user_lookup', table_name='responsibility_assignments')
    op.drop_index('idx_resource_lookup', table_name='responsibility_assignments')
    op.drop_index('idx_member_lookup', table_name='responsibility_assignments')
    op.drop_table('responsibility_assignments')

    # Note: UserRole enum values cannot be removed in PostgreSQL without recreating the enum
    # Manual intervention required to remove: super_admin, staff, pi, researcher, student
    # ### end Alembic commands ###
