"""initial_schema_postgres

Revision ID: 309c9004d180
Revises: 
Create Date: 2025-12-29 22:15:30.524227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309c9004d180'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_audit_id'), 'ingestion_audit', ['id'], unique=False)
    op.create_table('nodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_nodos_id'), 'nodos', ['id'], unique=False)
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=True),
    sa.Column('autores', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('url_origen', sa.Text(), nullable=True),
    sa.Column('canonical_doi', sa.String(length=100), nullable=True),
    sa.Column('path_pdf_local', sa.Text(), nullable=True),
    sa.Column('contenido_texto', sa.Text(), nullable=True),
    sa.Column('resumen_es', sa.Text(), nullable=True),
    sa.Column('resumen_en', sa.Text(), nullable=True),
    sa.Column('extracted_orcids', sa.Text(), nullable=True),
    sa.Column('has_valid_affiliation', sa.Boolean(), nullable=False),
    sa.Column('has_funding_ack', sa.Boolean(), nullable=False),
    sa.Column('anid_report_status', sa.String(length=50), nullable=False),
    sa.Column('last_audit_date', sa.DateTime(), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('doi_verification_status', sa.String(length=50), nullable=False),
    sa.Column('metrics_data', sa.JSON(), nullable=True),
    sa.Column('metrics_last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicaciones_canonical_doi'), 'publicaciones', ['canonical_doi'], unique=True)
    op.create_index(op.f('ix_publicaciones_id'), 'publicaciones', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('wps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('member_type', sa.String(length=50), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wp_id'], ['wps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_academic_members_id'), 'academic_members', ['id'], unique=False)
    op.create_index(op.f('ix_academic_members_rut'), 'academic_members', ['rut'], unique=True)
    op.create_table('meeting_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_minutes_id'), 'meeting_minutes', ['id'], unique=False)
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wp_id'], ['wps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_id'), 'proyectos', ['id'], unique=False)
    op.create_table('publication_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_chunks_id'), 'publication_chunks', ['id'], unique=False)
    op.create_table('publication_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('quartile', sa.String(length=10), nullable=True),
    sa.Column('jif', sa.Float(), nullable=True),
    sa.Column('is_international_collab', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id')
    )
    op.create_index(op.f('ix_publication_impact_id'), 'publication_impact', ['id'], unique=False)
    op.create_table('external_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['academic_members.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_metrics_id'), 'external_metrics', ['id'], unique=False)
    op.create_table('investigador_publicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['academic_members.id'], ),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigador_publicacion_id'), 'investigador_publicacion', ['id'], unique=False)
    op.create_table('member_wps',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['academic_members.id'], ),
    sa.ForeignKeyConstraint(['wp_id'], ['wps.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'wp_id')
    )
    op.create_table('proyecto_investigador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['academic_members.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_investigador_id'), 'proyecto_investigador', ['id'], unique=False)
    op.create_table('proyecto_nodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nodo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodos.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_nodo_id'), 'proyecto_nodo', ['id'], unique=False)
    op.create_table('proyecto_otrowp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['wp_id'], ['wps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_otrowp_id'), 'proyecto_otrowp', ['id'], unique=False)
    op.create_table('researcher_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.Column('is_auditable', sa.Boolean(), nullable=True),
    sa.Column('last_openalex_sync', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('name_variations', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('formalized_exit', sa.Boolean(), nullable=True),
    sa.Column('citaciones_totales', sa.Integer(), nullable=True),
    sa.Column('indice_h', sa.Integer(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=True),
    sa.Column('i10_index', sa.Integer(), nullable=True),
    sa.Column('url_foto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['academic_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_researcher_details_id'), 'researcher_details', ['id'], unique=False)
    op.create_index(op.f('ix_researcher_details_orcid'), 'researcher_details', ['orcid'], unique=True)
    op.create_table('student_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('co_tutor_id', sa.Integer(), nullable=True),
    sa.Column('thesis_title', sa.Text(), nullable=True),
    sa.Column('program', sa.String(length=255), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('funding_source', sa.String(length=255), nullable=True),
    sa.Column('program_start', sa.DateTime(), nullable=True),
    sa.Column('thesis_start', sa.DateTime(), nullable=True),
    sa.Column('defense_date', sa.DateTime(), nullable=True),
    sa.Column('document_paths', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['co_tutor_id'], ['academic_members.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['academic_members.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['academic_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_details_id'), 'student_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_details_id'), table_name='student_details')
    op.drop_table('student_details')
    op.drop_index(op.f('ix_researcher_details_orcid'), table_name='researcher_details')
    op.drop_index(op.f('ix_researcher_details_id'), table_name='researcher_details')
    op.drop_table('researcher_details')
    op.drop_index(op.f('ix_proyecto_otrowp_id'), table_name='proyecto_otrowp')
    op.drop_table('proyecto_otrowp')
    op.drop_index(op.f('ix_proyecto_nodo_id'), table_name='proyecto_nodo')
    op.drop_table('proyecto_nodo')
    op.drop_index(op.f('ix_proyecto_investigador_id'), table_name='proyecto_investigador')
    op.drop_table('proyecto_investigador')
    op.drop_table('member_wps')
    op.drop_index(op.f('ix_investigador_publicacion_id'), table_name='investigador_publicacion')
    op.drop_table('investigador_publicacion')
    op.drop_index(op.f('ix_external_metrics_id'), table_name='external_metrics')
    op.drop_table('external_metrics')
    op.drop_index(op.f('ix_publication_impact_id'), table_name='publication_impact')
    op.drop_table('publication_impact')
    op.drop_index(op.f('ix_publication_chunks_id'), table_name='publication_chunks')
    op.drop_table('publication_chunks')
    op.drop_index(op.f('ix_proyectos_id'), table_name='proyectos')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_meeting_minutes_id'), table_name='meeting_minutes')
    op.drop_table('meeting_minutes')
    op.drop_index(op.f('ix_academic_members_rut'), table_name='academic_members')
    op.drop_index(op.f('ix_academic_members_id'), table_name='academic_members')
    op.drop_table('academic_members')
    op.drop_table('wps')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_publicaciones_id'), table_name='publicaciones')
    op.drop_index(op.f('ix_publicaciones_canonical_doi'), table_name='publicaciones')
    op.drop_table('publicaciones')
    op.drop_index(op.f('ix_nodos_id'), table_name='nodos')
    op.drop_table('nodos')
    op.drop_index(op.f('ix_ingestion_audit_id'), table_name='ingestion_audit')
    op.drop_table('ingestion_audit')
    # ### end Alembic commands ###
