"""Add research map tables

Revision ID: 7075106367ed
Revises: g8h9i0j1k2l3
Create Date: 2026-01-21 11:22:21.234315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7075106367ed'
down_revision: Union[str, Sequence[str], None] = 'g8h9i0j1k2l3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_map_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('total_publications', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_map_snapshots_id'), 'research_map_snapshots', ['id'], unique=False)
    op.create_table('research_map_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('publication_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('cluster_label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['research_map_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_map_points_id'), 'research_map_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_map_points_id'), table_name='research_map_points')
    op.drop_table('research_map_points')
    op.drop_index(op.f('ix_research_map_snapshots_id'), table_name='research_map_snapshots')
    op.drop_table('research_map_snapshots')
    # ### end Alembic commands ###
