"""rename_publications_to_english

Revision ID: b3ec3c87cc84
Revises: 309c9004d180
Create Date: 2025-12-31 22:06:03.863286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3ec3c87cc84'
down_revision: Union[str, Sequence[str], None] = '309c9004d180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('canonical_doi', sa.String(length=100), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('resumen_es', sa.Text(), nullable=True),
    sa.Column('resumen_en', sa.Text(), nullable=True),
    sa.Column('extracted_orcids', sa.Text(), nullable=True),
    sa.Column('has_valid_affiliation', sa.Boolean(), nullable=False),
    sa.Column('has_funding_ack', sa.Boolean(), nullable=False),
    sa.Column('anid_report_status', sa.String(length=50), nullable=False),
    sa.Column('last_audit_date', sa.DateTime(), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('doi_verification_status', sa.String(length=50), nullable=False),
    sa.Column('metrics_data', sa.JSON(), nullable=True),
    sa.Column('metrics_last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_canonical_doi'), 'publications', ['canonical_doi'], unique=True)
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.drop_index(op.f('ix_publicaciones_canonical_doi'), table_name='publicaciones')
    op.drop_index(op.f('ix_publicaciones_id'), table_name='publicaciones')
    
    # 1. Drop old constraints referencing 'publicaciones'
    op.drop_constraint(op.f('external_metrics_publication_id_fkey'), 'external_metrics', type_='foreignkey')
    op.drop_constraint(op.f('investigador_publicacion_publicacion_id_fkey'), 'investigador_publicacion', type_='foreignkey')
    op.drop_constraint(op.f('publication_chunks_publicacion_id_fkey'), 'publication_chunks', type_='foreignkey')
    op.drop_constraint(op.f('publication_impact_publication_id_fkey'), 'publication_impact', type_='foreignkey')

    # 2. Drop the old table
    op.drop_table('publicaciones')

    # 3. Create new constraints referencing 'publications'
    op.create_foreign_key(None, 'external_metrics', 'publications', ['publication_id'], ['id'])
    op.create_foreign_key(None, 'investigador_publicacion', 'publications', ['publicacion_id'], ['id'])
    op.create_foreign_key(None, 'publication_chunks', 'publications', ['publicacion_id'], ['id'])
    op.create_foreign_key(None, 'publication_impact', 'publications', ['publication_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publication_impact', type_='foreignkey')
    op.create_foreign_key(op.f('publication_impact_publication_id_fkey'), 'publication_impact', 'publicaciones', ['publication_id'], ['id'])
    op.drop_constraint(None, 'publication_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('publication_chunks_publicacion_id_fkey'), 'publication_chunks', 'publicaciones', ['publicacion_id'], ['id'])
    op.drop_constraint(None, 'investigador_publicacion', type_='foreignkey')
    op.create_foreign_key(op.f('investigador_publicacion_publicacion_id_fkey'), 'investigador_publicacion', 'publicaciones', ['publicacion_id'], ['id'])
    op.drop_constraint(None, 'external_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('external_metrics_publication_id_fkey'), 'external_metrics', 'publicaciones', ['publication_id'], ['id'])
    op.create_table('publicaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('autores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('url_origen', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('canonical_doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('path_pdf_local', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contenido_texto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resumen_es', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resumen_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extracted_orcids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_valid_affiliation', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('has_funding_ack', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('anid_report_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_audit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('audit_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doi_verification_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metrics_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metrics_last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('publicaciones_pkey'))
    )
    op.create_index(op.f('ix_publicaciones_id'), 'publicaciones', ['id'], unique=False)
    op.create_index(op.f('ix_publicaciones_canonical_doi'), 'publicaciones', ['canonical_doi'], unique=True)
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_canonical_doi'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
