"""rename_summaries_to_english

Revision ID: e819df785656
Revises: b3ec3c87cc84
Create Date: 2025-12-31 22:22:01.524378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e819df785656'
down_revision: Union[str, Sequence[str], None] = 'b3ec3c87cc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('summary_es', sa.Text(), nullable=True))
    op.add_column('publications', sa.Column('summary_en', sa.Text(), nullable=True))
    op.drop_column('publications', 'resumen_en')
    op.drop_column('publications', 'resumen_es')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('resumen_es', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('publications', sa.Column('resumen_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('publications', 'summary_en')
    op.drop_column('publications', 'summary_es')
    # ### end Alembic commands ###
